### ISSUE TITLE
AttributeError: 'module' object has no attribute 'UID'

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.utils#114]
```
$ radical-stack 

  python               : 2.7.10
  pythonpath           : 
  virtualenv           : /Users/mturilli/Virtualenvs/RP-PAPER-IPDPS18

  radical.analytics    : v0.45.2-23-g24e4fe5@hackathon
  radical.pilot        : 0.47-v0.46.2-10-ged347dd4@experiment-ipdps2018
  radical.utils        : 0.47-v0.46-10-gc515db1@experiment-ipdps2018
  saga                 : 0.47-v0.46-5-g74fc3811@experiment-ipdps2018
```
```
Traceback (most recent call last):
  File "./wranglermp.py", line 780, in <module>
    wrangle_session(sdir, sid)
  File "./wranglermp.py", line 645, in wrangle_session
    sra_session = ra.Session(sid, 'radical.pilot', src=sdir)
  File "/Users/mturilli/Virtualenvs/RP-PAPER-IPDPS18/lib/python2.7/site-packages/radical/analytics/session.py", line 81, in __init__
    self._initialize_entities(profile)
  File "/Users/mturilli/Virtualenvs/RP-PAPER-IPDPS18/lib/python2.7/site-packages/radical/analytics/session.py", line 177, in _initialize_entities
    uid = event[ru.UID]
AttributeError: 'module' object has no attribute 'UID'
```

**Comment by andre-merzky** [comment]
The analytics devel branch should work with the experiment branches.  I still need to backport the hackathon work to RA devel for the next point release... :/  However, that will not include the `ru.UID` etc. definitions, as those are part of the conversion to profiling tuples which are not scheduled for release just yet...

**Comment by mturilli** [comment]
Thanks, this solve the issue. Should we leave this open until the fix is merged into devel and then released?

**Comment by andre-merzky** [comment]
Well, this is not part of the point release we are about to push out... - otherwise I don't mind either way...

**Comment by andre-merzky** [comment]
This has been released.
