### ISSUE TITLE
stderr has no method `isatty`

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.utils#125]
From Pavlo:

```
I get this error:

(harvester-venv) -bash-4.2$ 2017-10-20 20:10:55,808 panda.log.master: ERROR    Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/autofs/nccs-svm1_home1/psvirin/dev/harvester-venv/lib/python2.7/site-packages/pandaharvester/harvesterbody/submitter.py", line 157, in run
    submitterCore = self.pluginFactory.get_plugin(queueConfig.submitter)
  File "/autofs/nccs-svm1_home1/psvirin/dev/harvester-venv/lib/python2.7/site-packages/pandaharvester/harvestercore/plugin_factory.py", line 27, in get_plugin
    mod = __import__(moduleName)
  File "/autofs/nccs-svm1_home1/psvirin/dev/harvester-venv/lib/python2.7/site-packages/pandaharvester/harvestersubmitter/saga_submitter.py", line 1, in <module>
    import saga
  File "/autofs/nccs-svm1_home1/psvirin/dev/harvester-venv/lib/python2.7/site-packages/saga/__init__.py", line 53, in <module>
    _logger = ru.get_logger('radical.saga')
  File "/autofs/nccs-svm1_home1/psvirin/dev/harvester-venv/lib/python2.7/site-packages/radical/utils/logger.py", line 331, in get_logger
    handle = ColorStreamHandler(sys.stderr)
  File "/autofs/nccs-svm1_home1/psvirin/dev/harvester-venv/lib/python2.7/site-packages/radical/utils/logger.py", line 170, in __init__
    self._tty  = self.stream.isatty()
AttributeError: 'StdErrWrapper' object has no attribute 'isatty'
```

**Comment by andre-merzky** [comment]
This is unexpected, but should be easy to fix (we need to check for the attribute first).

**Comment by andre-merzky** [comment]
oudated.
