### ISSUE TITLE
Child initialization fails on Bridges

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.utils#148]
As of today I am getting this error on Bridges where an RP component can not be started. It does not happen at the same component every time. It has happened with input staging, the scheduler and the output staging. As a result, I think it is a Bridges issue or something has changed significantly on Bridges that I cannot understand.

```
2018-12-14 11:41:49,825: agent_0.staging.input.0: MainProcess                     : MainThread     : ERROR   : initialization failed (child agent_0.staging.input.0.child failed to come up [s])
Traceback (most recent call last):
  File "/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/test_run_full_3/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 505, in start
    (self._ru_childname, msg))
RuntimeError: child agent_0.staging.input.0.child failed to come up [s]
2018-12-14 11:42:33,266: agent_0.staging.input.0: MainProcess                     : MainThread     : INFO    : stop agent_0.staging.input.0 (28912 : 29163 : MainThread) [radical.utils.process.Default.start]
```

I am using the devel branched of RP and RU as shown in my stack:
```
  python               : 2.7.15
  pythonpath           :
  virtualenv           : EnTKlfs

  radical.entk         : 0.7.10-0.7.10-6-g902f83b@devel
  radical.pilot        : 0.50.19-v0.50.19-4-g70c584a@devel
  radical.utils        : 0.50.2-v0.50.2-5-g601a14c@devel
  saga                 : 0.50.0-v0.50.0-6-gf645140@fix-slurm_versioning
```

**Comment by iparask** [comment]
On Bridges: `/pylon5/mc3bggp/paraskev/radical.pilot.sandbox/test_run_full_3`

You will find 2 pilots in there. Both failed with that issue

**Comment by andre-merzky** [comment]
Is this still a problem?

**Comment by andre-merzky** [comment]
Please reopen if still needs action.

**Comment by AymenFJA** [comment]
Hello all , 

As I was trying to run my entk experiments on Bridges i am getting the following error : 

``` 
2019-03-20 22:17:31,133: agent_0.staging.output.0: MainProcess                     : MainThread     : ERROR   : initialization failed (child agent_0.staging.output.0.child failed to come up [Nones])
Traceback (most recent call last):
  File "/pylon5/mc3bggp/aymen/radical.pilot.sandbox/entk.session-2000-surf-31107/pilot.0000/rp_install/lib/python2.7/site-packages/radical/utils/process.py", line 505, in start
    (self._ru_childname, msg))
RuntimeError: child agent_0.staging.output.0.child failed to come up [Nones]
2019-03-20 22:18:20,511: agent_0.staging.output.0: MainProcess                     : MainThread     : INFO    : stop agent_0.staging.output.0 (12240 : 12340 : MainThread) [radical.utils.process.Default.start]
2019-03-20 22:18:21,908: agent_0.staging.output.0: MainProcess                     : MainThread     : INFO    : parent stops child  12240 -> 12340 [agent_0.staging.output.0]
2019-03-20 22:18:21,908: agent_0.staging.output.0: MainProcess                     : MainThread     : INFO    : send message: [agent_0.staging.output.0] STOP
2019-03-20 22:18:21,908: agent_0.staging.output.0: MainProcess                     : MainThread     : DEBUG   : ru_finalize_common()
2019-03-20 22:18:21,908: agent_0.staging.output.0: MainProcess                     : MainThread     : WARNING : publisher log_pubsub is not registered
2019-03-20 22:18:21,908: agent_0.staging.output.0: MainProcess                     : MainThread     : WARNING : publisher state_pubsub is not registered
2019-03-20 22:18:21,908: agent_0.staging.output.0: MainProcess                     : MainThread     : WARNING : publisher control_pubsub is not registered
2019-03-20 22:18:21,909: agent_0.staging.output.0: MainProcess                     : MainThread     : DEBUG   : agent_0.staging.output.0 close prof
2019-03-20 22:18:25,640: agent_0.staging.output.0: MainProcess                     : MainThread     : WARNING : failed to stop child - terminate: 12240 -> 12340 [agent_0.staging.output.0]
```
My `radical-stack`  is :

**Comment by andre-merzky** [comment]
thanks  Aymen!

**Comment by mturilli** [comment]
This is partially blocking the experiments for a paper. Around 50% of the runs are unsuccessful.

**Comment by AymenFJA** [comment]
update: I switched `radical.utils` to `devel` and the problems seems to be temporally fixed. I will keep updating this ticket if the error happens again.

**Comment by andre-merzky** [comment]
This is surprising but welcome news!

Aymen, if you have the time, please give the full devel RCT stack a try on bridges.  You will need a fresh VE for that to work.

**Comment by andre-merzky** [comment]
Closing as outdated: this code path has changed significantly by now.
