### ISSUE TITLE
TypeError: '>' not supported between instances of 'float' and 'str'

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.utils#189]
I am not certain if this is a bug in porting python3, but I just create a ticket for the record:

```
Traceback (most recent call last):
  File "00_getting_started.py", line 68, in <module>
    pilot = pmgr.submit_pilots(pdesc)
  File "/home/hrlee/venv3/entk/lib/python3.6/site-packages/radical/pilot/pilot_manager.py", line 502, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/hrlee/venv3/entk/lib/python3.6/site-packages/radical/pilot/compute_pilot.py", line 102, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/hrlee/venv3/entk/lib/python3.6/site-packages/radical/pilot/session.py", line 1003, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/hrlee/venv3/entk/lib/python3.6/site-packages/radical/saga/utils/pty_shell.py", line 244, in __init__
    interactive=self.interactive)
  File "/home/hrlee/venv3/entk/lib/python3.6/site-packages/radical/saga/utils/pty_shell_factory.py", line 199, in initialize
    self._initialize_pty(info['pty'], info)
  File "/home/hrlee/venv3/entk/lib/python3.6/site-packages/radical/saga/utils/pty_shell_factory.py", line 420, in _initialize_pty
    raise ptye.translate_exception (e)
  File "/home/hrlee/venv3/entk/lib/python3.6/site-packages/radical/saga/utils/pty_shell_factory.py", line 292, in _initialize_pty
    if time.time() - time_start > timeout:
TypeError: '>' not supported between instances of 'float' and 'str'
```

This is submitting rp.pilot to stampede2 with the stack:
```
hrlee ~/.github/radical-cybertools/radical.pilot/examples-->radical-stack 

  python               : 3.6.8
  pythonpath           : 
  virtualenv           : /home/hrlee/venv3/entk

  radical.pilot        : 0.90.1-v0.90.1-44-gbcf9a01@devel
  radical.saga         : 0.90.0
  radical.utils        : 0.90.3
```

**Comment by lee212** [comment]
This was a rp.saga issue, not rp.utils. Moved to radical-cybertools/radical.saga#746
