### ISSUE TITLE
pip install colorama is failing: AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.utils#195]
bootstrap_0.out includes errors:
```
verify module viability: radical.pilot   ...Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login2.hrlee.018241.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/pilot/__init__.py", line 10, in <module>
    import radical.utils as _ru
  File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login2.hrlee.018241.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/__init__.py", line 14, in <module>
    from .plugin_manager import PluginManager
  File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login2.hrlee.018241.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/plugin_manager.py", line 15, in <module>
    from .logger    import Logger
  File "/gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login2.hrlee.018241.0001/pilot.0000/rp_install/lib/python3.7/site-packages/radical/utils/logger.py", line 40, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
 failed
python installation cannot load module radical.pilot - abort
```
colorama is not recently introduced but python version (3.7) may contribute to this issue:
```
#
# install colorama
# cmd: /gpfs/alpine/csc393/scratch/hrlee/radical.pilot.sandbox/ve.ornl.summit.0.90.6/bin/pip --cert /gpfs/alpine/scratch/hrlee/csc393/radical.pilot.sandbox/rp.session.login2.hrlee.018241.0001/pilot.0000/../cacert.pem install colorama
#
Traceback (most recent call last):
  File "/gpfs/alpine/csc393/scratch/hrlee/radical.pilot.sandbox/ve.ornl.summit.0.90.6/bin/pip", line 3, in <module>
    import re
  File "/gpfs/alpine/csc393/scratch/hrlee/radical.pilot.sandbox/ve.ornl.summit.0.90.6/lib/python3.7/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by mturilli** [comment]
Could this be the culprit? https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

**Comment by andre-merzky** [comment]
I don't think there is much we can do, really.  I also saw this on one machine (can't remember where), but ultimately this seems to be caused by inconsistencies in pypi's dependency tree, and is triggered by earlier installs of other modules we only indirectly depend on.  We can't just uninstall those modules during installation either, that might break other user apps or modules.  So that problem is something the user or admin has to solve, I'm afraid...
