### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 105: ordinal not in range(128)

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.utils#226]
Entk script fails with the following error message:

```
Traceback (most recent call last):
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/utils/json_io.py", line 30, in read_json
    return parse_json(f.read())
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 105: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "summit_md.py", line 320, in <module>
    appman.run()
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/entk/appman/appmanager.py", line 414, in run
    self._rmgr._submit_resource_request()
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/entk/execman/rp/resource_manager.py", line 147, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/pilot/session.py", line 89, in __init__
    self._rcfgs   = ru.Config('radical.pilot.resource', name='*')
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/utils/config.py", line 306, in __init__
    scfg = read_json(sys_fname)
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/utils/json_io.py", line 33, in read_json
    raise ValueError('error parsing %s: %s' % (fname, e))
ValueError: error parsing /ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/pilot/configs/resource_yale.json: 'ascii' codec can't decode byte 0xe2
 in position 105: ordinal not in range(128)
```

and my stacks are:

```
(workflow-2) [hrlee@login5.summit workflow-2]$ radical-stack

  python               : 3.6.10
  pythonpath           : /sw/summit/xalt/1.2.0/site:/sw/summit/xalt/1.2.0/libexec
  virtualenv           : workflow-2

  radical.entk         : 1.0.2
  radical.pilot        : 1.1.1-devel_no_bulk_cb@hotfix-entk_hangup
  radical.saga         : 1.2.0
  radical.utils        : 1.2.0
```

I believe `encoding='utf-8'` would be necessary in parsing json files.

**Comment by andre-merzky** [comment]
Do you have a link to the json file which is being parsed?  Thanks.

**Comment by lee212** [comment]
```
>>> import glob
>>> l=glob.glob('*.json')
['agent_default_sa.json', 'resource_princeton.json', 'agent_default.json', 'pmgr_default.json', 'agent_osg.json', 'resource_fub.json', 'resource_osg.json', 'agent_cray.json', 'session_default.json', 'resource_ornl.json', 'resource_ncar.json', 'resource_local.json', 'resource_radical.json', 'agent_cray_aprun.json', 'agent_summit_sa.json', 'agent_rhea.json', 'resource_xsede.json', 'resource_debug.json', 'umgr_default.json', 'resource_aliases.json']
>>> for i in l:
...     try:
...         f=open(i)
...         data=json.load(f)
...     except:
...         print(i)
...
agent_default_sa.json
agent_default.json
pmgr_default.json
agent_osg.json
resource_osg.json
session_default.json
resource_ornl.json
resource_local.json
agent_summit_sa.json
resource_xsede.json
umgr_default.json
>>>
```

**Comment by andre-merzky** [comment]
Not sure I understand - those are the RP configs, but RU obviously can read the RP configs normally, because that's what it does all the time - so how can I reproduce this?  Do you have a specific json file which triggers this?

**Comment by lee212** [comment]
`resource_yale.json` is failed,
```
>>> for i in glob.glob("*.json"):
...     try:
...         data=ru.read_json(i)
...     except Exception as e:
...         print(e, i)
...
error parsing resource_yale.json: 'ascii' codec can't decode byte 0xe2 in position 105: ordinal not in range(128) resource_yale.json
```

**Comment by andre-merzky** [comment]
The RP branch you are on does not have that file.  I still can't reproduce...

**Comment by lee212** [comment]
I see. The resource file is obsolete, I remove it and won't see the UnicodeDecodeError.

What I suspect was that my `pip install . --upgrade` in my local repo with the branch uses the old `build` directory which contains the obsolete file.
