### ISSUE TITLE
Exception for RADICAL_BASE from sub-agent

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.utils#270]
```
Traceback (most recent call last):
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/bin/radical-pilot-agent", line 12,
in <module>
    import radical.utils as ru
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/lib/python3.7/site-packages/radical
/utils/__init__.py", line 14, in <module>
    from .plugin_manager import PluginManager
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/lib/python3.7/site-packages/radical
/utils/plugin_manager.py", line 15, in <module>
    from .logger    import Logger
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/lib/python3.7/site-packages/radical
/utils/logger.py", line 45, in <module>
    from   .debug     import import_module    as ru_import_module
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/lib/python3.7/site-packages/radical
/utils/debug.py", line 16, in <module>
    from .ids     import generate_id
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/lib/python3.7/site-packages/radical
/utils/ids.py", line 97, in <module>
    _BASE        = get_radical_base('utils')
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/lib/python3.7/site-packages/radical
/utils/misc.py", line 883, in get_radical_base
    rec_makedir(base)
  File "/gpfs/alpine/scratch/hrlee/med110/radical.pilot.sandbox/re.session.login2.hrlee.018603.0013/pilot.0000/rp_install/lib/python3.7/site-packages/radical
/utils/misc.py", line 896, in rec_makedir
    os.makedirs(target)
  File "/gpfs/alpine/med110/scratch/hrlee/radical.pilot.sandbox/ve.ornl.summit_prte.1.5.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/ccs/home/hrlee/.radical/utils/'
```

I tried `default_sa` but saw this error from `agent.1.err`. When I look at the code, it doesn't have an exception for ignoring existing *read-only* directory:
https://github.com/radical-cybertools/radical.utils/blob/9ff3a58ebbfb00062afd9c97b3e5b0f380d1cf51/src/radical/utils/misc.py#L890-L903

**Comment by mtitov** [comment]
@andre-merzky have a proposal (I think you already did something like this or at least tested it): force RP to manage the correct directory - use the value from resource config `"default_remote_workdir"` and set the env variable in pilot manager's [`_prepare_pilot`](https://github.com/radical-cybertools/radical.pilot/blob/devel/src/radical/pilot/pmgr/launching/default.py#L857)
```python
if not os.environ.get('RADICAL_BASE') and rcfg.get('default_remote_workdir'):
    os.environ['RADICAL_BASE'] = rcfg['default_remote_workdir']
```

**Comment by andre-merzky** [comment]
`_prepare_pilot` is on the client side, so that won't help with the agent side BASE - or am I missing something?  But in general yes, the launcher should add `RADICAL_BASE` to the SAGA job env, and ideally point it to the resource sandbox on the target machine.
