### ISSUE TITLE
session id generation not fool proof

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.utils#33]
```
2015:03:12 11:29:35 3958   MainThread   radical.pilot         : [ERROR   ] session create failed
Traceback (most recent call last):
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical/pilot/session.py", line 225, in __init__
    db_name = database_name)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical/pilot/db/database.py", line 105, in new
    dbs.create(sid, name, creation_time)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical/pilot/db/database.py", line 138, in create
    raise DBEntryExistsException ("Session '%s' already exists." % sid)
DBEntryExistsException: Session 'rp.session.netbook.mark.016506.0002' already exists.
Error during execution: Couldn't create new session (database URL 'mongodb://ec2-54-221-194-147.compute-1.amazonaws.com:24242/' incorrect?): Session 'rp.session.netbook.mark.016506.0002' already exists.
2015:03:12 11:29:35 3958   MainThread   radical.pilot         : [DEBUG   ] session rp.session.netbook.mark.016506.0002 closing
Exception AttributeError: "'Session' object has no attribute '_dbs'" in <bound method Session.__del__ of <radical.pilot.session.Session object at 0x10dd69f50>> ignored

```

Had to rerun a couple of times until the counter in the tmp file got above a certain value again.

**Comment by marksantcroos** [comment]
Also see https://github.com/radical-cybertools/RepEx/issues/29.

Ran into it myself today too again.

I dont think its acceptable to run into issues like this because we choose to implement our own id generation.

**Comment by andre-merzky** [comment]
This should be fixed in utils, a pull request is pending.  I  still think that human-readable IDs are rather beneficial, but of course there is the option to use UUIDs...

**Comment by andre-merzky** [comment]
This is fixed and merged.
