### ISSUE TITLE
RTD build fails

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.utils#403]
RTD command sequence:
```sh
git clone --depth 1 https://github.com/radical-cybertools/radical.utils .
git fetch origin --force --prune --prune-tags --depth 50 refs/heads/feature/parallel_cluster:refs/remotes/origin/feature/parallel_cluster
git checkout --force origin/feature/parallel_cluster
git clean -d -f -f
cat .readthedocs.yml
asdf global python 3.7.17
python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH 
python -m pip install --upgrade --no-cache-dir pip setuptools
python -m pip install --upgrade --no-cache-dir sphinx readthedocs-sphinx-ext
python -m pip install --exists-action=w --no-cache-dir -r requirements-docs.txt
python -m pip install --upgrade --upgrade-strategy only-if-needed --no-cache-dir .
 ```
 
Failure:
```sh
      Traceback (most recent call last):
        File "/home/docs/checkouts/readthedocs.org/user_builds/radicalutils/checkouts/feature-parallel_cluster/setup.py", line 156, in get_version
          '%s/%s'   % (_mod_root, _sdist_name))  # copy into tree
        File "/home/docs/.asdf/installs/python/3.7.17/lib/python3.7/shutil.py", line 248, in copy
          copyfile(src, dst, follow_symlinks=follow_symlinks)
        File "/home/docs/.asdf/installs/python/3.7.17/lib/python3.7/shutil.py", line 120, in copyfile
          with open(src, 'rb') as fsrc:
      FileNotFoundError: [Errno 2] No such file or directory: 'dist/radical_utils-1.51.0.tar.gz'
```

Note that the basically same setup does work for all other RCT modules.

**Comment by mtitov** [comment]
Both "stable" and "devel" versions were [re]build correctly 
https://radicalutils.readthedocs.io

**Comment by haampie** [comment]
What commit fixed this?
